// packages/svelte/src/Nodeflow.svelte
<script lang="ts">
  import type { NodeflowData, NodeflowSettings } from "@nodeflow-lib/vanilla";
  import { createVanillaNodeflow } from "@nodeflow-lib/vanilla";

  interface Props {
    id: string;
    options?: Partial<NodeflowSettings>;
    onready?: (data: NodeflowData) => void;
    [key: string]: unknown;
  }

  let { id, options, onready, ...restProps }: Props = $props();

  let container: HTMLDivElement;

  $effect(() => {
    const nodeflowData = createVanillaNodeflow(id, container, options);
    onready?.(nodeflowData);
  });
</script>

<div bind:this={container} style="width: 100%; height: 100%;" {...restProps}></div>

// packages/react/src/Nodeflow.tsx
import { useEffect, useRef } from "react";
import type { HTMLAttributes } from "react";
import { createVanillaNodeflow, NodeflowRegistry } from "@nodeflow-lib/vanilla";
import type { NodeflowData, NodeflowSettings } from "@nodeflow-lib/vanilla";

type NodeflowProps = HTMLAttributes<HTMLDivElement> & {
  id: string;
  options?: Partial<NodeflowSettings>;
  onReady?: (data: NodeflowData) => void;
};

export const Nodeflow = ({
  id,
  options,
  onReady,
  style,
  ...rest
}: NodeflowProps) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const nodeflowData = createVanillaNodeflow(id, container, options);

    if (onReady) {
      onReady(nodeflowData);
    }

    return () => {
      NodeflowRegistry.get().removeNodeflow(id);
      container.innerHTML = "";
    };
  }, []);

  return (
    <div
      ref={containerRef}
      style={{ width: "100%", height: "100%", ...style }}
      {...rest}
    />
  );
};
