// examples/ReactApp/src/App.tsx
import { Nodeflow } from "@nodeflow/react";
import type { NodeflowData } from "@nodeflow/react";

function nodeDisplay({
  node,
}: {
  node: { id: string; position: { x: number; y: number } };
}): HTMLElement {
  const wrapper = document.createElement("div");
  Object.assign(wrapper.style, {
    padding: "14px 18px",
    minWidth: "140px",
    background: "#16213e",
    borderRadius: "8px",
    border: "1px solid #0f3460",
    color: "#e2e2e2",
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    fontSize: "13px",
    lineHeight: "1.4",
  });
  const title = document.createElement("strong");
  title.textContent = `Node ${node.id}`;
  Object.assign(title.style, {
    display: "block",
    marginBottom: "2px",
    fontSize: "14px",
    color: "#fff",
  });
  const subtitle = document.createElement("span");
  subtitle.textContent = `Position ${node.position.x.toFixed(
    0,
  )}, ${node.position.y.toFixed(0)}`;
  Object.assign(subtitle.style, { opacity: "0.5", fontSize: "11px" });
  wrapper.appendChild(title);
  wrapper.appendChild(subtitle);
  return wrapper;
}

export default function App() {
  function handleReady(data: NodeflowData) {
    function addNode(x: number, y: number, inputs: number, outputs: number) {
      const node = data.addNode({ position: { x, y }, display: nodeDisplay });
      if (inputs > 0) {
        const section = node.addConnectorSection({ id: "inputs" });
        for (let i = 0; i < inputs; i++)
          section.addConnector({ id: `in-${i}` });
      }
      if (outputs > 0) {
        const section = node.addConnectorSection({ id: "outputs" });
        for (let i = 0; i < outputs; i++)
          section.addConnector({ id: `out-${i}` });
      }
      return node;
    }

    const start = addNode(80, 100, 0, 2);
    const config = addNode(80, 300, 0, 1);
    const transform = addNode(380, 60, 2, 1);
    const validate = addNode(380, 260, 2, 1);
    const merge = addNode(380, 460, 1, 1);
    const output = addNode(700, 160, 2, 1);
    const logger = addNode(700, 400, 2, 0);

    data.addConnection({
      sourceNodeId: start.id,
      sourceConnectorId: "out-0",
      destinationNodeId: transform.id,
      destinationConnectorId: "in-0",
    });
    data.addConnection({
      sourceNodeId: start.id,
      sourceConnectorId: "out-1",
      destinationNodeId: validate.id,
      destinationConnectorId: "in-0",
    });
    data.addConnection({
      sourceNodeId: config.id,
      sourceConnectorId: "out-0",
      destinationNodeId: validate.id,
      destinationConnectorId: "in-1",
    });
    data.addConnection({
      sourceNodeId: transform.id,
      sourceConnectorId: "out-0",
      destinationNodeId: output.id,
      destinationConnectorId: "in-0",
    });
    data.addConnection({
      sourceNodeId: validate.id,
      sourceConnectorId: "out-0",
      destinationNodeId: output.id,
      destinationConnectorId: "in-1",
    });
    data.addConnection({
      sourceNodeId: merge.id,
      sourceConnectorId: "out-0",
      destinationNodeId: logger.id,
      destinationConnectorId: "in-0",
    });
    data.addConnection({
      sourceNodeId: output.id,
      sourceConnectorId: "out-0",
      destinationNodeId: logger.id,
      destinationConnectorId: "in-1",
    });
  }

  return <Nodeflow id="main" onReady={handleReady} />;
}

// examples/SvelteApp/src/App.svelte
<script lang="ts">
  import { Nodeflow } from "@nodeflow/svelte";
  import type { NodeflowData } from "@nodeflow/svelte";

  interface DisplayNode {
    id: string;
    position: { x: number; y: number };
  }

  function nodeDisplay({ node }: { node: DisplayNode }): HTMLElement {
    const wrapper = document.createElement("div");
    Object.assign(wrapper.style, {
      padding: "14px 18px",
      minWidth: "140px",
      background: "#16213e",
      borderRadius: "8px",
      border: "1px solid #0f3460",
      color: "#e2e2e2",
      fontFamily: "'Segoe UI', system-ui, sans-serif",
      fontSize: "13px",
      lineHeight: "1.4",
    });

    const title = document.createElement("strong");
    title.textContent = `Node ${node.id}`;
    Object.assign(title.style, {
      display: "block",
      marginBottom: "2px",
      fontSize: "14px",
      color: "#fff",
    });

    const subtitle = document.createElement("span");
    subtitle.textContent = `Position ${node.position.x.toFixed(0)}, ${node.position.y.toFixed(0)}`;
    Object.assign(subtitle.style, {
      opacity: "0.5",
      fontSize: "11px",
    });

    wrapper.appendChild(title);
    wrapper.appendChild(subtitle);
    return wrapper;
  }

  function handleReady(nodeflowData: NodeflowData) {
    function addNode(x: number, y: number, inputs: number, outputs: number) {
      const node = nodeflowData.addNode({
        position: { x, y },
        display: nodeDisplay,
      });

      if (inputs > 0) {
        const section = node.addConnectorSection({ id: "inputs" });
        for (let i = 0; i < inputs; i++) {
          section.addConnector({ id: `in-${i}` });
        }
      }

      if (outputs > 0) {
        const section = node.addConnectorSection({ id: "outputs" });
        for (let i = 0; i < outputs; i++) {
          section.addConnector({ id: `out-${i}` });
        }
      }

      return node;
    }

    const start = addNode(80, 100, 0, 2);
    const config = addNode(80, 300, 0, 1);

    const transform = addNode(380, 60, 2, 1);
    const validate = addNode(380, 260, 2, 1);
    const merge = addNode(380, 460, 1, 1);

    const output = addNode(700, 160, 2, 1);
    const logger = addNode(700, 400, 2, 0);

    function connect(
      srcId: string,
      srcConnector: string,
      dstId: string,
      dstConnector: string,
    ) {
      nodeflowData.addConnection({
        sourceNodeId: srcId,
        sourceConnectorId: srcConnector,
        destinationNodeId: dstId,
        destinationConnectorId: dstConnector,
      });
    }

    connect(start.id, "out-0", transform.id, "in-0");
    connect(start.id, "out-1", validate.id, "in-0");
    connect(config.id, "out-0", validate.id, "in-1");
    connect(transform.id, "out-0", output.id, "in-0");
    connect(validate.id, "out-0", output.id, "in-1");
    connect(merge.id, "out-0", logger.id, "in-0");
    connect(output.id, "out-0", logger.id, "in-1");
  }
</script>

<Nodeflow id="main" onready={handleReady} />
